export const styles = {
  container: {
    zIndex: 50,
    my: { xs: 6, lg: 12 },
  },
  stickyHeader: {
    position: "sticky",
    top: "50px",
  },
  violetCircle: {
    width: 80,
    height: 80,
    bgcolor: "#f5f3ff",
    borderRadius: "50%",
    position: "absolute",
    top: -12,
    left: 0,
    transform: "translateX(50%)",
    filter: "blur(48px)",
    opacity: 0.3,
    pointerEvents: "none",
  },
  headerWrapper: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    position: "relative",
  },
  headerText: {
    bgcolor: "#1a1443",
    color: "#ffffff",
    position: "absolute",
    left: 0,
    px: "20px",
    py: "12px",
    fontSize: "1.25rem",
    borderRadius: "6px",
    zIndex: 2,
  },
  line: {
    width: "100%",
    height: "2px",
    bgcolor: "#1a1443",
  },
  projectsWrapper: {
    pt: 10,
  },
  projectsList: {
    mt: "10%",
    display: "flex",
    flexDirection: "column",
    gap: 3,
  },
  stickyProject: (index: number) => ({
    position: "sticky",
    top: `calc(${index + 1} * ${index ? "5rem" : "6.5rem"})`,
    width: "100%",
    mx: "auto",
    maxWidth: 672,
    zIndex: index + 1,
  }),
  cardBox: {
    boxSizing: "border-box",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 2,
    boxShadow: "0 0 30px rgba(0,0,0,0.3)",
    transition: "all 0.5s",
  },
};
