export const styles = {
  container: {
    pt: "5%",
    mt: { xs: "90px", md: "50px" },
    position: "relative",
  },
  blurCircle: {
    width: "100px",
    height: "100px",
    bgcolor: "#ede9fe",
    borderRadius: "50%",
    position: "absolute",
    top: "70px",
    left: "50%",
    transform: "translate(-50%,-50%)",
    filter: "blur(48px)",
    opacity: 0.2,
  },
  titleWrapper: {
    position: "absolute",
    left: "50%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    transform: "translate(-50%, -50%)",
    top: "70px",
  },
  titleText: {
    fontWeight: 400,
    bgcolor: "#1a1443",
    fontSize: "18px",
    px: 2,
    py: 1.1,
    borderRadius: 2,
  },
  titleLine: {
    width: 250,
    height: 5,
    bgcolor: "#1a1443",
    position: "absolute",
    zIndex: "-1",
  },
  marqueeContainer: { width: "100%", my: 12 },
  skillCard: {
    width: "9rem",
    minWidth: "fit-content",
    height: "fit-content",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    transition: "all 0.5s ease",
    m: { xs: 1.5, sm: 2.5 },
    borderRadius: "0.5rem",
    position: "relative",
    cursor: "pointer",
    "&:hover": { transform: "scale(1.15)" },
  },
  skillBox: {
    height: "100%",
    width: "100%",
    borderRadius: "0.5rem",
    border: "1px solid #1f223c",
    backgroundColor: "#11152c",
    transition: "all 0.5s ease",
    "&:hover": { borderColor: "#8b5cf6" },
  },
  topGradientLineWrapper: {
    display: "flex",
    justifyContent: "center",
    transform: "translateY(-1px)",
  },
  topGradientLineInner: { width: "75%" },
  topGradientLine: {
    height: "1px",
    width: "100%",
    background: "linear-gradient(to right, transparent, #8b5cf6, transparent)",
  },
  skillContent: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
    p: 3,
  },
  skillImageBox: { height: { xs: "2rem", sm: "2.5rem" } },
  skillImage: {
    height: "100%",
    width: "auto",
    borderRadius: "0.5rem",
  },
  skillText: {
    color: "white",
    fontSize: { xs: "0.875rem", sm: "1.125rem" },
  },
};
