export const styles = {
  aboutContainer: {
    display: "flex",
    flexDirection: { xs: "column-reverse", md: "row" },
    my: { xs: "20%", md: "10%" },
    mt: { xs: "100px", md: "10%" },
    position: "relative",
    justifyContent: "center",
    alignItems: "center",
    gap: { xs: 3, md: 0 },
  },
  textContainer: {
    width: { xs: "100%", md: "50%" },
  },
  subHeading: {
    fontSize: "clamp(1.125rem, 1.0769rem + 0.1923vw, 1.25rem)",
    color: "var(--primary-color)",
    fontWeight: 500,
  },
  description: {
    fontSize: "clamp(0.875rem, 0.742rem + 0.4255vw, 1.125rem)",
  },
  imageSection: {
    display: "grid",
    placeItems: "center",
    width: { xs: "100%", md: "50%" },
  },
  aboutLabelContainer: {
    position: "absolute",
    top: { xs: "-80px", md: 40 },
    right: { md: "-20px" },
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    transform: { md: "rotate(90deg)" },
  },
  aboutLabel: {
    fontWeight: 400,
    bgcolor: "#1a1443",
    fontSize: "18px",
    px: 2,
    py: 1.1,
    borderRadius: 2,
  },
  aboutLabelLine: {
    width: 200,
    height: 5,
    bgcolor: "#1a1443",
    position: "absolute",
    zIndex: "-1",
    left: { md: 0 },
  },
  cardContainer: {
    width: 300,
    height: 300,
    perspective: 1000,
    borderRadius: 50,
    "& #inner": {
      animation: "myFlip 4s ease-in-out infinite",
      "@keyframes myFlip": {
        "0%": { transform: "rotateY(0deg)" },
        "50%": { transform: "rotateY(180deg)" },
        "100%": { transform: "rotateY(360deg)" },
      },
    },
    "&:hover #inner": {
      animationPlayState: "paused",
    },
  },
  cardInner: {
    position: "relative",
    width: "100%",
    height: "100%",
    textAlign: "center",
    transition: "transform 1s",
    transformStyle: "preserve-3d",
  },
  cardFront: {
    position: "absolute",
    width: "100%",
    height: "100%",
    backfaceVisibility: "hidden",
    borderRadius: 50,
    overflow: "hidden",
    boxShadow: 5,
    transform: "rotateY(180deg)",
  },
  profileImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  cardBack: {
    bgcolor: "blue",
    position: "absolute",
    width: "100%",
    height: "100%",
    backfaceVisibility: "hidden",
    borderRadius: 50,
    overflow: "hidden",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    boxShadow: 5,
    backgroundImage:
      "linear-gradient(62deg, #4158D0 0%, #7c3aed 16%, #ec4899 100%)",
  },
  cardText: {
    fontWeight: 600,
    fontSize: "25px",
    textShadow: "2px 4px black",
  },
};
