export const styles = {
  anchoreLink: {
    color: "var(--secondary-color)",
    transition: "0.5s",
    display: "block",
    height: 30,
    width: 30,
    "&:hover": {
      cursor: "pointer",
      transform: "scale(1.2)",
    },
  },
  container: {
    display: "flex",
    justifyContent: "space-between",
    flexDirection: { xs: "column-reverse", md: "row" },
    alignItems: "center",
    mt: "4%",
  },
  leftSection: { width: { xs: "100%", md: "50%" } },
  socialLinks: { display: "flex", gap: 3, my: "5%" },
  buttonsContainer: { mt: "5%", gap: 2, display: "flex" },
  gradientBorder: {
    textDecoration: "none",
    display: "inline-block",
    borderRadius: "9999px",
    backgroundImage: "linear-gradient(to right, #7c3aed, #ec4899)",
    padding: "1px",
    transition: "all 0.3s ease",
    "&:hover": {
      backgroundImage: "linear-gradient(to right, #ec4899, #7c3aed)",
    },
  },
  contactButton: {
    px: { xs: 1.5, md: 4 },
    py: { xs: 1, md: 1.5 },
    borderRadius: "9999px",
    backgroundColor: "#0d1224",
    color: "#fff",
    fontSize: { xs: "0.75rem", md: "0.875rem" },
    fontWeight: { xs: 500, md: 600 },
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    display: "flex",
    alignItems: "center",
    gap: 0.8,
    transition: "all 0.2s ease-out",
    "&:hover": { gap: "0.75rem", backgroundColor: "#0d1224" },
  },
  resumeButton: {
    textDecoration: "none",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.25rem",
    px: { xs: 1.5, md: 4 },
    py: { xs: 1, md: 1.5 },
    borderRadius: "9999px",
    backgroundImage: "linear-gradient(to right, #ec4899, #7c3aed)",
    fontSize: { xs: "0.75rem", md: "0.875rem" },
    fontWeight: { xs: 500, md: 600 },
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    color: "#fff",
    transition: "all 0.2s ease-out",
    "&:hover": {
      gap: "0.75rem",
      backgroundImage: "linear-gradient(to right, #7c3aed, #ec4899)",
      textDecoration: "none",
      color: "#fff",
    },
  },
  rightSection: {
    width: { xs: "100%", md: "45%" },
    position: "relative",
    borderRadius: "12px",
    border: "1px solid #1b2c68a0",
    background: "linear-gradient(to right, #0d1224, #0a0d37)",
    "&::before": {
      content: '""',
      position: "absolute",
      top: 0,
      left: 0,
      width: "100%",
      height: "1px",
      borderTopLeftRadius: "12px",
      borderTopRightRadius: "12px",
      background:
        "linear-gradient(to right, transparent, #ec4899, #7c3aed, transparent)",
    },
  },
  windowHeader: { px: { xs: 2, lg: 4 }, py: 2 },
  windowDotsContainer: { display: "flex", gap: 1 },
  redDot: {
    width: 12,
    height: 12,
    borderRadius: "50%",
    bgcolor: "error.light",
  },
  orangeDot: { width: 12, height: 12, borderRadius: "50%", bgcolor: "orange" },
  greenDot: {
    width: 12,
    height: 12,
    borderRadius: "50%",
    bgcolor: "success.light",
  },
  codeBox: {
    borderTop: "2px solid #312e81",
    px: { xs: 2, lg: 4 },
    py: { xs: 2, lg: 4 },
    fontFamily: "monospace",
    fontSize: { xs: "0.75rem", md: "0.875rem", lg: "1rem" },
    color: "white",
  },
  indent1: { ml: { xs: 2, lg: 4 } },
  indent2: { ml: { xs: 4, lg: 8 } },
  indent3: { ml: { xs: 6, lg: 12 } },
  indent2Gray: { ml: { xs: 4, lg: 8 }, color: "gray" },
  indent1Gray: { ml: { xs: 2, lg: 4 }, color: "gray" },
  pinkText: { color: "#ec4899", mr: 1 },
  whiteText: { color: "white", mr: 1 },
  grayText: { color: "gray" },
  yellowText: { color: "#fcd34d" },
  orangeText: { color: "orange" },
  greenText: { color: "green" },
  cyanText: { color: "cyan" },
};
export const helloText = (color?: string) => ({
  color: color ? `var(--${color}-color)` : "white",
  fontSize: "clamp(1.875rem, 1.6106rem + 1.0577vw, 2.5625rem);",
  fontWeight: 800,
});
